#!/bin/sh

IFACE=$1
ACTION=$2

echo "$ACTION"
echo "$IFACE"
case ${IFACE} in
    eth*|usb*|en*)
        case ${ACTION} in
            up)
                if [ -f /usr/bin/logger ];then
                    /usr/bin/logger "Disabling wifi radio"
                    echo "Disabling wifi radio"
                else
                    echo "Disabling wifi radio"
                fi
                nmcli radio wifi off
                ;;
            down)
                if [ -f /usr/bin/logger ];then
                    /usr/bin/logger "Activating wifi radio"
                    echo "Activating wifi radio"
                else
                    echo "Activating wifi radio"
                fi
                nmcli radio wifi on
                ;;
        esac
        ;;
esac
