#!/bin/bash

##############################################################################
#
#  ps_wombat - a series of process scripts I use
#  (c) Steven Saus 2021
#  Licensed under the MIT license
#
##############################################################################

wombat=$(echo "$1")
#echo "$wombat"
bob=$(ps aux | grep -v "grep" | grep -v "psx2" | grep -c -e "$wombat" )
#echo $bob
if [ $bob -gt 0 ];then
    echo "$1 is up."
    exit 0
else
    echo "$1 is down"
    exit 99
fi
