#!/bin/bash


########################################################################
#
# 	Network up/down notification for network-manager and WICD
#   Literally just used to emit a call to another script in userspace so
#   we drop root privileges ASAP; not passing anything; everything is in 
#   userspace
#   
########################################################################

case "$2" in

    down)   
        sudo -u USERNAME /usr/bin/bash -c 'whoami;echo $USER;/usr/local/bin/network-middle-manager down' # outputs USERNAME's user name twice

        ;;
    up) 
        sudo -u USERNAME /usr/bin/bash -c 'whoami;echo $USER;/usr/local/bin/network-middle-manager down' # outputs USERNAME's user name twice

        ;;

# Edit this for obvs reasons to the nmm script
